version: '3.8'

services:
  # Laravel application container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080  # Expose Nginx on port 8080
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: your_database
      DB_USERNAME: your_username
      DB_PASSWORD: your_password
    volumes:
      - .:/var/www  # Mount the project directory
    depends_on:
      - php
      - mysql

  # PHP-FPM container
  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - .:/var/www
    networks:
      - app_network

  # Nginx container
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    ports:
      - 8080:8080
    depends_on:
      - php
    networks:
      - app_network

  # MySQL container
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_username
      MYSQL_PASSWORD: your_password
    ports:
      - 3306:3306
    networks:
      - app_network

  # Vite container (for development)
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 5173:5173  # Vite dev server (default port)
    volumes:
      - .:/var/www  # Mount project directory for real-time updates
    depends_on:
      - app
    environment:
      VITE_SERVER: "http://localhost:5173"  # Adjust Vite server URL if necessary

networks:
  app_network:
    driver: bridge
